FROM ubuntu:trusty

RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends \
        build-essential \
        curl

# https://www.linuxfromscratch.org/lfs/view/stable/chapter08/openssl.html

ARG OPENSSL_VERSION="1.1.1m"
    
RUN cd /tmp && \
    curl -O -k https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz && \
    tar -xf openssl-${OPENSSL_VERSION}.tar.gz && \
    cd openssl-${OPENSSL_VERSION} && \
    ls && \
    ./config \
        --openssldir=/usr/local/openssl \
        --prefix=/usr/local/openssl && \
    make && \
    make install

# these env variables will be set in the container by default, avoid
ENV PATH=/usr/local/openssl/bin${PATH:+:$PATH}
ENV LD_LIBRARY_PATH=/usr/local/openssl/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

# https://www.linuxfromscratch.org/blfs/view/stable/general/python3.html

RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends \
        zlib1g-dev

ARG PYTHON_VERSION="3.10.1"

RUN cd /tmp && \
    curl -O -k https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz && \
    tar -xf Python-${PYTHON_VERSION}.tar.xz && \
    cd Python-${PYTHON_VERSION} && \
    ./configure \
        --enable-shared \
        --prefix=/usr/local/python \
        --with-openssl=/usr/local/openssl && \
    make && \
    make install

